# Generated by Django 3.1.5 on 2021-05-05 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('postcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('type_of', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('is_owner', models.BooleanField(default=False)),
                ('is_seeker', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('id_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croomies_api.media')),
            ],
        ),
        migrations.CreateModel(
            name='Sport_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sport', models.ManyToManyField(to='croomies_api.Sport')),
                ('id_user', models.ManyToManyField(to='croomies_api.User')),
            ],
        ),
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_min', models.IntegerField()),
                ('budget_max', models.IntegerField()),
                ('response_one', models.FloatField()),
                ('response_two', models.FloatField()),
                ('response_three', models.FloatField()),
                ('response_four', models.FloatField()),
                ('response_five', models.FloatField()),
                ('id_adress_search', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='croomies_api.address')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croomies_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Music_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_music', models.ManyToManyField(to='croomies_api.Music')),
                ('id_user', models.ManyToManyField(to='croomies_api.User')),
            ],
        ),
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skip', models.BooleanField(default=False)),
                ('like', models.BooleanField(default=False)),
                ('id_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croomies_api.seeker')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croomies_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Habitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('rooms_nb', models.IntegerField()),
                ('area', models.IntegerField()),
                ('description', models.TextField()),
                ('compatibility_score', models.FloatField()),
                ('is_furnished', models.BooleanField()),
                ('price', models.IntegerField()),
                ('id_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='croomies_api.address')),
            ],
        ),
        migrations.CreateModel(
            name='Film_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_film', models.ManyToManyField(to='croomies_api.Film')),
                ('id_user', models.ManyToManyField(to='croomies_api.User')),
            ],
        ),
    ]
