# Generated by Django 3.1.5 on 2021-04-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croomies_api', '0002_auto_20210428_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.IntegerField(),
        ),
    ]
