# Generated by Django 3.1.5 on 2021-04-29 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('croomies_api', '0003_auto_20210428_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('postcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Matcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='media',
            name='type_of',
        ),
        migrations.AddField(
            model_name='user',
            name='id_media',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='croomies_api.media'),
        ),
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='User_sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sport', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='croomies_api.sport')),
                ('id_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='croomies_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_min', models.IntegerField()),
                ('budget_max', models.IntegerField()),
                ('response_one', models.FloatField()),
                ('response_two', models.FloatField()),
                ('response_three', models.FloatField()),
                ('response_four', models.FloatField()),
                ('response_five', models.FloatField()),
                ('id_adress_search', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='croomies_api.address')),
                ('id_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='croomies_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Music_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_music', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='croomies_api.music')),
                ('id_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='croomies_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skip', models.BooleanField(default=False)),
                ('like', models.BooleanField(default=False)),
                ('id_matcher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='croomies_api.matcher')),
                ('id_seeker', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='croomies_api.seeker')),
            ],
        ),
        migrations.AddField(
            model_name='matcher',
            name='id_seeker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='croomies_api.seeker'),
        ),
        migrations.CreateModel(
            name='Habitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('rooms_nb', models.IntegerField()),
                ('area', models.IntegerField()),
                ('description', models.TextField()),
                ('compatibility_score', models.FloatField()),
                ('is_furnished', models.BooleanField()),
                ('id_address', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='croomies_api.address')),
            ],
        ),
        migrations.CreateModel(
            name='Film_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_film', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='croomies_api.film')),
                ('id_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='croomies_api.user')),
            ],
        ),
    ]
