# Generated by Django 3.2 on 2021-05-05 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('croomies_api', '0004_auto_20210429_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sport', models.ManyToManyField(to='croomies_api.Sport')),
            ],
        ),
        migrations.RemoveField(
            model_name='user_sport',
            name='id_sport',
        ),
        migrations.RemoveField(
            model_name='user_sport',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='matching',
            name='id_matcher',
        ),
        migrations.AddField(
            model_name='habitation',
            name='price',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matching',
            name='id_user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='croomies_api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='type_of',
            field=models.CharField(default=-1, max_length=20),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='film_user',
            name='id_film',
        ),
        migrations.AddField(
            model_name='film_user',
            name='id_film',
            field=models.ManyToManyField(to='croomies_api.Film'),
        ),
        migrations.RemoveField(
            model_name='film_user',
            name='id_user',
        ),
        migrations.AddField(
            model_name='film_user',
            name='id_user',
            field=models.ManyToManyField(to='croomies_api.User'),
        ),
        migrations.AlterField(
            model_name='habitation',
            name='id_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='croomies_api.address'),
        ),
        migrations.AlterField(
            model_name='matching',
            name='id_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croomies_api.seeker'),
        ),
        migrations.RemoveField(
            model_name='music_user',
            name='id_music',
        ),
        migrations.AddField(
            model_name='music_user',
            name='id_music',
            field=models.ManyToManyField(to='croomies_api.Music'),
        ),
        migrations.RemoveField(
            model_name='music_user',
            name='id_user',
        ),
        migrations.AddField(
            model_name='music_user',
            name='id_user',
            field=models.ManyToManyField(to='croomies_api.User'),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='id_adress_search',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='croomies_api.address'),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croomies_api.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croomies_api.media'),
        ),
        migrations.DeleteModel(
            name='Matcher',
        ),
        migrations.DeleteModel(
            name='User_sport',
        ),
        migrations.AddField(
            model_name='sport_user',
            name='id_user',
            field=models.ManyToManyField(to='croomies_api.User'),
        ),
    ]
