# Generated by Django 3.2 on 2021-05-27 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('postcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CroomiesUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('is_owner', models.BooleanField(default=False)),
                ('is_seeker', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('is_media', models.BooleanField(default=False)),
                ('identity_card', models.URLField(blank=True, null=True)),
                ('student_card', models.URLField(blank=True, null=True)),
                ('proof_address_self', models.URLField(blank=True, null=True)),
                ('proof_address_guarantor', models.URLField(blank=True, null=True)),
                ('identity_card_guarantor', models.URLField(blank=True, null=True)),
                ('proof_income_self', models.URLField(blank=True, null=True)),
                ('proof_income_guarantor', models.URLField(blank=True, null=True)),
                ('tax_notice_self', models.URLField(blank=True, null=True)),
                ('tax_notice_guarantor', models.URLField(blank=True, null=True)),
                ('property_tax_guarantor', models.URLField(blank=True, null=True)),
                ('apl_certificate', models.URLField(blank=True, null=True)),
                ('nbr_rooms', models.IntegerField(blank=True, null=True)),
                ('is_whole_habitation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Date_slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Habitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('rooms_nb', models.IntegerField()),
                ('area', models.IntegerField()),
                ('description', models.TextField()),
                ('compatibility_score', models.FloatField()),
                ('is_furnished', models.BooleanField()),
                ('price', models.IntegerField()),
                ('id_address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='croomies_api.address')),
                ('id_date_slots', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='croomies_api.date_slots')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('type_of', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_min', models.IntegerField()),
                ('budget_max', models.IntegerField()),
                ('number_of_room', models.IntegerField()),
                ('is_empty_habitation', models.BooleanField(default=False)),
                ('searching_from', models.DateField()),
                ('searching_to', models.DateField()),
                ('response_one', models.FloatField()),
                ('response_two', models.FloatField()),
                ('response_three', models.FloatField()),
                ('response_four', models.FloatField()),
                ('response_five', models.FloatField()),
                ('id_adress_search', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='croomies_api.address')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croomies_api.croomiesuser')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Time_slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('id_habitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croomies_api.habitation')),
                ('id_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croomies_api.seeker')),
            ],
        ),
        migrations.CreateModel(
            name='Sport_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sport', models.ManyToManyField(to='croomies_api.Sport')),
                ('id_user', models.ManyToManyField(to='croomies_api.CroomiesUser')),
            ],
        ),
        migrations.CreateModel(
            name='Roomate_in_habitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_habitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croomies_api.habitation')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croomies_api.croomiesuser')),
            ],
        ),
        migrations.CreateModel(
            name='Music_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_music', models.ManyToManyField(to='croomies_api.Music')),
                ('id_user', models.ManyToManyField(to='croomies_api.CroomiesUser')),
            ],
        ),
        migrations.CreateModel(
            name='Media_habitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_habitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croomies_api.habitation')),
                ('id_media', models.ManyToManyField(to='croomies_api.Media')),
            ],
        ),
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skip', models.BooleanField(default=False)),
                ('like', models.BooleanField(default=False)),
                ('id_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croomies_api.seeker')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croomies_api.croomiesuser')),
            ],
        ),
        migrations.AddField(
            model_name='habitation',
            name='id_time_slots',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='croomies_api.time_slots'),
        ),
        migrations.AddField(
            model_name='habitation',
            name='id_user_poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='croomies_api.croomiesuser'),
        ),
        migrations.CreateModel(
            name='Film_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_film', models.ManyToManyField(to='croomies_api.Film')),
                ('id_user', models.ManyToManyField(to='croomies_api.CroomiesUser')),
            ],
        ),
        migrations.AddField(
            model_name='croomiesuser',
            name='id_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='croomies_api.media'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('id_habitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croomies_api.habitation')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croomies_api.croomiesuser')),
            ],
        ),
    ]
