# Generated by Django 3.2.2 on 2021-05-11 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('croomies_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CroomiesUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('is_owner', models.BooleanField(default=False)),
                ('is_seeker', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('id_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='croomies_api.media')),
            ],
        ),
        migrations.CreateModel(
            name='Roomate_in_habitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_habitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croomies_api.habitation')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croomies_api.croomiesuser')),
            ],
        ),
        migrations.CreateModel(
            name='Media_habitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_habitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croomies_api.habitation')),
                ('id_media', models.ManyToManyField(to='croomies_api.Media')),
            ],
        ),
        migrations.AlterField(
            model_name='film_user',
            name='id_user',
            field=models.ManyToManyField(to='croomies_api.CroomiesUser'),
        ),
        migrations.AlterField(
            model_name='matching',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croomies_api.croomiesuser'),
        ),
        migrations.AlterField(
            model_name='music_user',
            name='id_user',
            field=models.ManyToManyField(to='croomies_api.CroomiesUser'),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croomies_api.croomiesuser'),
        ),
        migrations.AlterField(
            model_name='sport_user',
            name='id_user',
            field=models.ManyToManyField(to='croomies_api.CroomiesUser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
