# Generated by Django 3.2 on 2021-05-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croomies_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker',
            name='number_of_room',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
