# Generated by Django 3.2.2 on 2021-06-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croomies_api', '0002_remove_croomiesuser_drugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='croomiesuser',
            name='cluster',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
