# Generated by Django 3.2 on 2021-06-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croomies_api', '0002_remove_croomiesuser_drugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croomiesuser',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
