# Generated by Django 3.2.2 on 2021-05-12 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('croomies_api', '0002_auto_20210511_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitation',
            name='id_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='croomies_api.address'),
        ),
    ]
