# Generated by Django 3.2.2 on 2021-05-26 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('croomies_api', '0003_alter_habitation_id_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date_slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Time_slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='croomiesuser',
            name='apl_certificate',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='croomiesuser',
            name='identity_card',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='croomiesuser',
            name='identity_card_guarantor',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='croomiesuser',
            name='is_media',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='croomiesuser',
            name='proof_address_guarantor',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='croomiesuser',
            name='proof_address_self',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='croomiesuser',
            name='proof_income_guarantor',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='croomiesuser',
            name='proof_income_self',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='croomiesuser',
            name='property_tax_guarantor',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='croomiesuser',
            name='student_card',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='croomiesuser',
            name='tax_notice_guarantor',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='croomiesuser',
            name='tax_notice_self',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habitation',
            name='id_user_poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='croomies_api.croomiesuser'),
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('id_habitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croomies_api.habitation')),
                ('id_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croomies_api.seeker')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('id_habitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croomies_api.habitation')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croomies_api.croomiesuser')),
            ],
        ),
        migrations.AddField(
            model_name='habitation',
            name='id_date_slots',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='croomies_api.date_slots'),
        ),
        migrations.AddField(
            model_name='habitation',
            name='id_time_slots',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='croomies_api.time_slots'),
        ),
    ]
