# Generated by Django 3.2 on 2021-05-27 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('croomies_api', '0003_auto_20210527_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seeker',
            name='response_five',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='response_four',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='response_one',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='response_three',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='response_two',
        ),
    ]
