# Generated by Django 3.2 on 2021-05-27 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('croomies_api', '0004_auto_20210527_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker',
            name='budget_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='budget_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='id_adress_search',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='croomies_api.address'),
        ),
    ]
