# Generated by Django 3.2 on 2021-06-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croomies_api', '0004_alter_croomiesuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croomiesuser',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
