# Generated by Django 3.2 on 2021-06-21 15:32

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('croomies_api', '0005_alter_croomiesuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croomiesuser',
            name='password',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=20)),
        ),
    ]
