# Generated by Django 3.2 on 2021-05-27 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('croomies_api', '0005_auto_20210527_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker',
            name='id_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='croomies_api.croomiesuser'),
        ),
    ]
