# Generated by Django 3.2 on 2021-05-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croomies_api', '0007_auto_20210527_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='where_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seeker',
            name='where_city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='seeker',
            name='where_country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='seeker',
            name='where_postcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
