# Generated by Django 3.2 on 2021-06-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('croomies_api', '0003_croomiesuser_cluster'),
        ('croomies_api', '0009_alter_croomiesuser_password'),
    ]

    operations = [
    ]
